#pragma once

#define APP_TITLE "WHOCAM-RTSP"
#define APP_VERSION "1.0"

#define WIFI_SSID "WHOCAM-RTSP"
#define WIFI_PASSWORD "starkenburg"
#define CONFIG_VERSION "1.2"

#define OTA_PASSWORD "starkenburg"

#define RTSP_PORT 554
#define DEFAULT_CAMERA_CONFIG "TTGO T-CAM"
#define DEFAULT_FRAME_DURATION "20"
#define DEFAULT_FRAME_BUFFERS "2"
#define DEFAULT_FRAME_SIZE "SVGA (800x600)"
#define DEFAULT_JPEG_QUALITY "12"
